piVersion: apps/v1
name: my-dotnet-chart
version: 0.1.0
kind: Deployment
metadata:
  name: dotnet-app
  namespace: defaul
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: acr0720.azurecr.io/july20:1.0.0
        ports:
        - containerPort: 80

