apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: admin
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: aks0712
        image: aks0712.azurecr.io/image0712:1.0.0
        ports:
        - containerPort: 80