apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: Admin
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: megh
        image: meghanapurimitla/megh:1.0.0
        ports:
        - containerPort: 80