apiVersion: apps/v1
kind: Deployment
metadata:
  name: seven
  namespace: default
  labels:
    app: seven
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seven
  template:
    metadata:
      annotations:
        network.kubernetes.io/network-policy: "seven-network-policy"
      labels:
        app: seven
    spec:
      containers:
        - name: seven
          image: acr0720.azurecr.io/july20:1.0.0
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: meghana
      serviceAccountName: seven-service-account
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
