# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-seven  # Use .Release.Name to get the release name set by Helm
  namespace: {{ .Release.Namespace }}  # Use .Release.Namespace to get the namespace set by Helm
  labels:
    app: {{ .Release.Name }}-seven
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-seven
  template:
    metadata:
      annotations:
        network.kubernetes.io/network-policy: "seven-network-policy"
      labels:
        app: {{ .Release.Name }}-seven
    spec:
      containers:
        - name: seven
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: {{ .Values.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbePath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            periodSeconds: {{ .Values.periodSeconds }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodeSelectorKey }}
                    operator: In
                    values:
                      - {{ .Values.nodeSelectorValue }}
