apiVersion: apps/v1
kind: Deployment
metadata:
  name: seven
  namespace: default
  labels:
    app: seven
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seven
  template:
    metadata:
      annotations:
        network.kubernetes.io/network-policy: "seven-network-policy"
      labels:
        app: seven
    spec:
      containers:
        - name: seven
          image: acr0720.azurecr.io/july20:1.0.0
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: meghana
      serviceAccountName: seven-service-account

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seven-ingress
  namespace: default
spec:
  rules:
    - host: myapp.example.com   # Replace this with your actual domain or IP address
      http:
        paths:
          - path: /                # Change this if you want a different base path
            pathType: Prefix
            backend:
              service:
                name: seven
                port:
                  number: 5000        # Change this to match the containerPort above
