apiVersion: apps/v1
kind: Deployment
metadata:
  name: july
  labels:
    app: july20
spec:
  replicas: 2
  selector:
    matchLabels:
      app: july20 
  template:
    metadata:
      labels:
        app: july20
    spec:
      containers:
      - name: july20
        image: acr0720.azurecr.io/july20:1.0.0
        ports:
        - containerPort: 80