apiVersion: apps/v1
kind: Deployment
metadata:
  name: seven
  labels:
    app: seven
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seven
  template:
    metadata:
      labels:
        app: seven
      annotations:
        network.kubernetes.io/network-policy: "seven-network-policy"  # Add this line to associate the NetworkPolicy
    spec:
      serviceAccountName: seven-service-account
      containers:
      - name: seven
        image: acr0720.azurecr.io/july20:1.0.0
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
        - name: meghana
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 3
