apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: seven-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: seven
  minReplicas: 2
  maxReplicas: 10    # Set the maximum number of replicas you want for autoscaling
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50   # Adjust this as needed for your application's CPU utilization target
