apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: seven-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: seven
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: allowed-source-app
