apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: seven-pdb
  namespace: meghana
spec:
  minAvailable: 1  # Minimum number of available pods during disruptions
  selector:
    matchLabels:
      app: seven
