apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seven-new-role-binding   # Provide a new name for the RoleBinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: seven-service-account   # Replace with the name of your ServiceAccount
    namespace: default
roleRef:
  kind: ClusterRole              # Replace with "ClusterRole" or "Role" as needed
  name: view                     # Replace with the desired role name
  apiGroup: rbac.authorization.k8s.io
