apiVersion: v1
kind: Service
metadata:
  name: seven-service
  namespace: default
spec:
  selector:
    app: seven
  ports:
    - protocol: TCP
      port: 80           # The port to access the service internally
      targetPort: 5000   # The port your application listens on inside the pod
