apiVersion: v1
kind: Service
metadata:
  name: seven
  namespace: default
  labels:
    app: seven
spec:
  selector:
    app: seven
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000   # Change this to match the containerPort in the Deployment
  type: LoadBalancer
