apiVersion: v1
kind: Service
metadata:
  name: seven-service
  namespace: default
spec:
  selector:
    app: seven
  ports:
    - protocol: TCP
      port: 80        # Port on which the service will listen
      targetPort: 5000   # Port on which your application is running inside the pod
  type: LoadBalancer   # Change this from ClusterIP to LoadBalancer
