# Default values for repo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2  # Change the replicaCount to 2

image:
  repository: acr0720.azurecr.io/july20  # Update the image repository to your desired image repository
  pullPolicy: IfNotPresent
  tag: 1.0.0  # Update the image tag to the specific version you want to use

imagePullSecrets:
  - name: meghana  # Add your image pull secrets if required

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: seven-service-account  # Update the service account name to your desired service account

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

affinity: {}
